### ISSUE TITLE
G0 command

### ISSUE THREAD

**Issue by electric-2000** [cncgoko/Goko#19]
Not sure if this is a TinyG issue or something in your code.
When running a file, I issue G0Z12.000 to bring the tool to the start point of the cut and when finished I use G0Z12.000 to clear the part to return the tool to home. On sample below the ending G0Z12.000 does not get executed, but the following line G0X0.000Y0.000 does.

G90
G17
G21
G0Z12.000
G0X0.000Y0.000
M03 S11000
G0X118.619Y33.587Z12.000
G1Z-3.000F600.0
G1X119.133Y31.929
G1X119.665Y30.301
...
...
...
...
...
G1X118.619Y33.587
G0Z12.000
G0X0.000Y0.000
M05

This is not related to the latest build, but it still exists with the latest.

**Comment by cncgoko** [comment]
HI,

I tried and streamed the given example to TinyG (only removed the ```...``` lines) and it works like a charm (using Goko 0.0.2 and TinyG 0.97 firmware build 440.18).
Anything in the log file ? 
You'll find 2 logs file :
- a .log file in the log/ folder
- or the most recent log file in workspace/.metadata/ folder

**Comment by electric-2000** [comment]
Here is the log file and the entire gcode.

**Comment by cncgoko** [comment]
You can use Github Gist (https://gist.github.com/). I think you can add files in them.

**Comment by electric-2000** [comment]
Here is the log file. I noticed that when the G0Z12.00 was executed there was beep coming from the board or stepper.
 
https://gist.github.com/06dded43ee739b7b6ebd.git

**Comment by cncgoko** [comment]
Gist URL is not valid.

**Comment by electric-2000** [comment]
That is the HTTPS clone URL that was supplied, go figure...try this
https://gist.github.com/electric-2000/06dded43ee739b7b6ebd

**Comment by cncgoko** [comment]
The complete file run without issue on my side and there is nothing in the log file.
This could be a TinyG 440.20 as it's the edge. Current master is 440.18 and that's the version I'm using.
Any error in the most recent log file in  ```{GOKO_FOLDER}/workspace/.metadata/``` folder ?

**Comment by electric-2000** [comment]
Here is link to my workspace .log file-
https://gist.github.com/electric-2000/ff3b70edfa35de761d45

Sorry to drag you into this, here is where I am-
FWIW- 440.20 is called a Master so I figured it was good.
Loaded Chilipeppr and had the same issue, so it's not GOKO
Downgraded to 440.18 and it's working, so it's a 440.20 has an issue, guess I should file a bug with them.

Thanks Again

**Comment by aldenhart** [comment]
Please get me your machine configuration and I will check this out. Did it seem like the motor was trying to move on the G0 Z12 move?

**Comment by electric-2000** [comment]
It's working great with 440.18, it's 440.20 that has the issue
Here is a link to the config-
https://gist.github.com/electric-2000/315abcfec95d7181c87b

**Comment by electric-2000** [comment]
Here are a couple shots to the hardware configuration-
http://www.3dimensionaltools.com/wp-content/uploads/Komodo-Right-Wiring.jpg
http://www.3dimensionaltools.com/wp-content/uploads/Komodo-Right.jpg

**Comment by aldenhart** [comment]
I've only had the chance to test in a cursory way but the Z axis seems to be working fine on both 440.18 and 440.20. I notice that your jerk settings are very high for a screw axis for Z. Screw axes are typically happiest when the jerk is set to between 50 (M) and 500 (M). You might try that.

Other things I noticed about the configs
- A motor timeout of 0.1 sec is very low for a belt driven machine. You usually want this at least 2 seconds so you don't get drift when motion stops
- The X and Y pulleys are very close but not the same. Usually these are the same. Were these adjusted for positioning?
- If the Z screw is a typically 1.25mm screw (stock Shapeoko) then the value of 1.24 is too low by a hair
- The feedrate maxes should be below the velocity maxes.

**Comment by electric-2000** [comment]
I come from the Mach3 world and as you can tell my settings were all over the place! I lowered the Z jerk and brought the feedrates below the max velocity...that took care of the stall I was getting on the Z retract.
After testing in 440.18 I moved back up to 440.20 and the problem went away!
As for the travel settings, I did a calibration test early on and this is what I came up with, I'll need to revisit that again to make sure my moves are calibrated.

Thanks Alden for jumping in here and helping out.
