### ISSUE TITLE
High CPU while connected to serial (TinyG)

### ISSUE THREAD

**Issue by perfectphase** [cncgoko/Goko#22]
Not a high priority as it works, but when I connect to the TinyG, the CPU pops up to 25% on a quad core, 50% on a dual core, even while the system is idle.
Disconnecting drops the CPU down normal levels.
It also seems if the system is left idle for a minute then disconnected/reconnected the CPU will not drop and when reconnected it will double (50% on Quad, 100% on dual)

**Comment by cncgoko** [comment]
I noticed that as well while using it on the actual machine.
Search for improvements is planned for next release.

**Comment by cncgoko** [comment]
Fixed in release 0.3.0
