### ISSUE TITLE
Pendant Idea

### ISSUE THREAD

**Issue by hk89** [cncgoko/Goko#31]
I needed a way of controlling my machine while the computer is away
so I had a wireless numpad laying around. I tried it with the software, but
it only jogged the machine! I couldn't use fast jog, slow jog, pause,
resume or abort. I head on to settings and I
couldn't find anything related.
 
So, I came up with a new idea. Why not implement a way of assigning
keyboard keys in the settings to control the machine? 
 
Maybe this will help people that don't have the ShuttleXpress like me!

**Comment by cncgoko** [comment]
Keyboard keys assignement is now available in Goko 0.3.4
