### ISSUE TITLE
Console filtering feature question

### ISSUE THREAD

**Issue by hk89** [cncgoko/Goko#34]
Hi,

I love the new feature of filtering the console. However, I do not know how to use arguments. Is there any thing I can read somewhere to help me? I could not find it anywhere. Maybe using predefned buttons for these arguments that a user can click on to add them in the "Parameter" box would be quite handy.

**Comment by cncgoko** [comment]
Hi,

The documentation is available here http://docs.goko.fr/
The section about serial console explains it : http://docs.goko.fr/master/documentation/index.html#_serial_connection

Let me know if the documentation requires more explanation.

**Comment by hk89** [comment]
Nice documentation! Thanks!

I guess I have to learn those patterns for some time! :D
