### ISSUE TITLE
Error when connecting

### ISSUE THREAD

**Issue by hk89** [cncgoko/Goko#40]
Hi,

I found that when connecting to grbl 1.1 on a nano, Goko (0.3.4) was not able to communicate with it. DRO's state is 'undefined', queue can not be started, I can not send serial commands and command panel buttons are grayed out. See attached image.

I did not change any of the serial communication preferences.
![untitled](https://cloud.githubusercontent.com/assets/24245215/26741713/d2b7fb50-47da-11e7-9921-2ff6072f4994.png)

**Comment by cncgoko** [comment]
Hi, 

What's the value of Flow Control ? 
It should be turned off for Grbl.

**Comment by hk89** [comment]
I believe that I freshly flashed grbl 1.1 on a new nano with blank EEPROM, so I think that the flow control is off by default. Am I right?

**Comment by cncgoko** [comment]
Yes but did you turn it off in Goko as well ?

**Comment by hk89** [comment]
I don't know what happened but I found that it was set to "RTS/CTS". I don't remember changing that!

I set it to XON/XOFF and now running!

**Comment by cncgoko** [comment]
You'd better turn it off completely ! I think Grbl does not support flow control.
