### ISSUE TITLE
bug in gcode viewer

### ISSUE THREAD

**Issue by mhk1367** [cncgoko/Goko#45]
hi and thanks
gcode viewer have bug when i change home position in grbl. please solve it.

**Comment by mhk1367** [comment]
when i click zoom to fit
![2017-08-28_13-25-49](https://user-images.githubusercontent.com/26634452/29766648-ba6b12fe-8bf4-11e7-9cf4-5baba394d18e.jpg)
![2017-08-28_13-26-50](https://user-images.githubusercontent.com/26634452/29766649-ba710ba0-8bf4-11e7-84c3-020b11c08f2a.jpg)

**Comment by mhk1367** [comment]
i solved. thx

**Comment by cncgoko** [comment]
Hi @mhk1367 

How did you solve this issue ? 
Anyway, I reopen this issue, because it need to be fixed in the application code.

Thx for the report.
