### ISSUE TITLE
Obversation - The character ? is not a valid expression in Serial Console Filters

### ISSUE THREAD

**Issue by Jere51a** [cncgoko/Goko#49]
The serial filter feature is really powerful.  I used a <.*. filter to squelch the GRBL status traffic.  Without it, the serial console is just about unusable.  I would also like to suppress the "?" requests.  When I tried to set up this filter, Goko complained that for ?, "Pattern is not a valid expression".  Hope I'm not missing something simple.  Kindly advise at your convenience.

**Comment by cncgoko** [comment]
@Jere51a Valid filter for status query is \?
I will update the documentation asap.
