### ISSUE TITLE
Sign-up failure on discuss.goko.fr when using GitHub as auth provider

### ISSUE THREAD

**Issue by justinclift** [cncgoko/Goko#53]
Note - this probably isn't **really** exactly the right place to report this failure, but I'm not seeing any better options and putting it here should still get in front of the right people. :wink:

---

Just tried to sign up for discuss.goko.fr, mainly to ask what you're using for generating 4th axis G-Code for TinyG (eg Fusion360? something else? etc).  Mainly because it's the current task I'm working through (eg getting a Fusion 360 post processor to output 4th axis G-Code for g2core).

Anyway... the sign up process for discuss.goko.fr errors out when choosing GitHub as the auth provider:

![discuss goko fr github auth signup failure1](https://user-images.githubusercontent.com/406299/38460827-d93041c2-3ab9-11e8-8e00-bbd1a57e4185.png)

Is it expected to work? :smile:

**Comment by cncgoko** [comment]
Hello Justin,

Sorry for the late answer. I have less time than expected to work on Goko, unfortunately...
I will check the Github login thing when possible. It worked, because that's how I created my account :)

I'll let you know.

**Comment by justinclift** [comment]
Cool. :smile:

As a thought, the Goko Gitter doesn't seem to be mentioned here on the GitHub repo, nor on goko.fr.  I only accidentally stumbled across it the other day when looking at discuss.goko.fr.  If you're still interested in expanding out the Community, adding a "CHAT" menu item to goko.fr header (like the discuss.goko.fr) page might be useful + some mention here in the repo too. :smile:

**Comment by cncgoko** [comment]
That was kind of the initial idea, but then I decided that narrowing down the communication channel would make the information easier to find. Forum + github + chat is a lot of different places to check. The best compromise to me is to have the forum as a discussion place, and the Github use only to report bug, or request features.
